version: '3.6'
services:
  points-service:
    container_name: points-service
    restart: always
    image: ${IMAGE}
    networks:
      - dc-net
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      M_TOKEN: ${M_TOKEN}
      DB_NAME: points-service
      CONTAINER_PORT: 80
#     REPLACEME

#    ports:
#      - 82:81
networks:
  dc-net:
    external: true