version: '3.6'
services:
  points-service:
    container_name: points-service
    restart: always
    build: .
    networks:
      - dc-net
    environment:
#      DB_HOST: ${DB_HOST}
#      DB_USER: ${DB_USER}
#      DB_PASS: ${DB_PASS}
      DB_NAME: points-service

      #CONFIG SERVER
      CONFIG_SERVER_URL: http://config_server
      SERVICE_NAME: points-service
      NAMESPACE: dev-dc
      M_TOKEN: ${M_TOKEN}
      #END CONFIG SERVER

      CONTAINER_PORT: 80
#     REPLACEME

    ports:
      - 82:80
networks:
  dc-net:
    external: true