version: '3.6'
services:
  points_service:
    container_name: points_service
    restart: always
    image: ${IMAGE}
    networks:
      - dc-net
    environment:
      DB_NAME: points-service

      #CONFIG SERVER
      CONFIG_SERVER_URL: http://config_server
      SERVICE_NAME: points-service
      M_TOKEN: ${M_TOKEN}
      #END CONFIG SERVER

#    ports:
#      - 82:81
networks:
  dc-net:
    external: true